In [1]:
import numpy as np  # Import NumPy library
print("Imported NumPy successfully.\n")

Imported NumPy successfully.



Valid Sudoku

In [26]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [28]:
row = np.sum(s , axis = 1)
col = np.sum(s , axis = 0)

for r , c in zip(row , col):
    if r != 45 or c != 45:
        print("Invalid Sudoku")
        break
else:
    print("Sudoku is valid for rows and columns")

Sudoku is valid for rows and columns


In [29]:
for i in range(0 , 9 , 3):
    for j in range(0 , 9 , 3):
        block = s[i:i+3 , j:j+3]
        if np.sum(block) != 45:
            print("Invalid Sudoku")
            break
else:
    print("Sudoku is valid for all 3x3 blocks")


Sudoku is valid for all 3x3 blocks


General Questions

In [120]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
#  age,math,science
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [32]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [35]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [ ]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [44]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [ ]:
#Get details of the student who scored more than 90 in Math.
data[data[: , 1] > 90]

array([[19, 92, 88]])

In [105]:
#Increase Math marks of all students by 5.
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [102]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])

3

In [109]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[: , 1 : ] , axis=0)

array([86.6, 83.2])

In [116]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [121]:
#Replace all Science marks < 75 with 0.
data[data[: , 2] < 75 , 2] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])